- name: stat node
  stat:
    path: /opt/{{ node_version }}/bin/
  register: node_stat

- name: download nodejs
  get_url:
    dest: /tmp/nodejs.tar.xz
    url: "{{ node_download_url }}"
  when: not node_stat.stat.exists


- name: unarchive node js
  become: true
  unarchive:
    src: /tmp/nodejs.tar.xz
    dest: /opt/
    remote_src: true
  when: not node_stat.stat.exists
  

    
  
- name: append extra config to zshrc
  blockinfile:
    state: present 
    marker: '#load nodejs path'
    block: |
      PATH=${PATH}:/opt/{{ node_version }}/bin/
    dest: ~/.zshrc
  when: not node_stat.stat.exists


